datadog:
  apiKey: 07dd098280c741d1e0f8b19587d8f5ce
  enabled: true
  step: PT10S
  metrics:
    apiKey: 07dd098280c741d1e0f8b19587d8f5ce
    period: 10
    enabled: false

spring:
  application:
    name: datadog-demo-api
  profiles:
    active: dev
  data:
    mongodb:
      uri: "mongodb+srv://jschmidt:n0JTV6TKTliuKeen@demo-cluster.pusgic3.mongodb.net/demo-data?retryWrites=true&w=majority"

metrics:
  frequency: 5 seconds                       # Default is 1 second.
  reporters:
    - type: datadog
      prefix: demoapi
      transport:
        type: udp
        prefix:                             # Optional. Default is (empty)
        statsdHost: "localhost"             # Optional. Default is "localhost"
        port: 8125                          # Optional. Default is 8125

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "metrics", "datadog", "bindings", "beans", "env", "loggers", "streamsbindings"]
  metrics:
    export:
      datadog:
        api-key: 07dd098280c741d1e0f8b19587d8f5ce
        application-key: e5de7f6e769e49d537d3485fe51742e716697344
        host-tag: ${spring.application.name}
        index: metrics
        step: 15s
  security:
    enabled: false
