spring:
  application:
    name: datadog-reactive-demo-api
  profiles:
    active: dev
  data:
    mongodb:
      uri: "mongodb+srv://jschmidt:n0JTV6TKTliuKeen@demo-cluster.pusgic3.mongodb.net/demo-data?retryWrites=true&w=majority"

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "metrics", "datadog", "bindings", "beans", "env", "loggers", "streamsbindings"]
        
  metrics:
    export:
      datadog:
        api-key: 07dd098280c741d1e0f8b19587d8f5ce
        application-key: e5de7f6e769e49d537d3485fe51742e716697344
        host-tag: ${spring.application.name}
        index: metrics
        step: 15s
  security:
    enabled: false
