version: '3.8'

services:
  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    hostname: datadog-agent
    environment:
      DD_API_KEY: 07dd098280c741d1e0f8b19587d8f5ce
      DD_APM_ENABLED: true
      DD_SITE: datadoghq.com
      DD_APM_NON_LOCAL_TRAFFIC: true
    cap_add:
      - SYS_PTRACE
    pid: host
    privileged: true
    ports:
      - 8080:8080
      - 8125:8125
      - 8126:8126
    networks:
      - datadog-network
    restart: unless-stopped

  datadog-demo-api:
    image: jpaulo0866/datadog-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - datadog-agent
    ports:
      - 8080:8080
      - 8125:8125
      - 8126:8126
    networks:
      - datadog-network

networks:
  datadog-network:
    driver: bridge