version: '3.8'

services:
  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    environment:
      DD_API_KEY: 07dd098280c741d1e0f8b19587d8f5ce
      DD_APM_ENABLED: true
      DD_SITE: datadoghq.com
      DD_APM_NON_LOCAL_TRAFFIC: true
    restart: unless-stopped

  datadog-demo-api:
    image: jpaulo0866/datadog-api
    depends_on:
      - datadog-agent
    ports:
      - "80:8080"
      - "443:8080"
